CC = gcc

all: ex1 ex2
	@echo "All exercises are built."

ex1: ex1a ex1b ex1c
	@echo "Exercise 1 is built."

ex1a: ex1/ex1a.c
	$(CC) -o ex1/ex1a ex1/ex1a.c

ex1b: ex1/ex1b.c
	$(CC) -o ex1/ex1b ex1/ex1b.c

ex1c: ex1/ex1c.c
	$(CC) -o ex1/ex1c ex1/ex1c.c

ex2: ex2/ex2.c
	$(CC) -o ex2/ex2 ex2/ex2.c
	@echo "Exercise 2 is built."